services:
  - type: web
    name: prestige-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    envVars:
      - key: DISCORD_TOKEN
        value: your-token-here
      - key: OCR_SPACE_API_KEY
        value: your-api-key-here
