services:
  - type: web
    name: prestige-bot
    env: python
    buildCommand: ./render-build.sh
    startCommand: python main.py
    plan: free
    envVars:
      - key: DISCORD_TOKEN
        value: your_bot_token_here
