services:
  - type: web
    name: cherrow-prestige-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: OCR_SPACE_API_KEY
        sync: false
